version: '3.4'

services:
  weatherapi3:
    image: ${DOCKER_REGISTRY-}weatherapi3
    build:
      context: .
      dockerfile: Dockerfile
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
       SA_PASSWORD: "Pa55word!"
       ACCEPT_EULA: "Y"